
version: '3'
services: 
    node:
        image: node:10.16.0
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        ports:
            - 3000:3000
            - 5001:5001
        command: bash -c "yarn install && yarn build && yarn start"
        expose:
            - "3000"
            - "5001"
    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/mongo:/data/db
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_PASSWORD_FILE: MONGO_PASSWORD
            MONGO_INITDB_DATABASE: $MONGO_DB